#Mysql config
spring.datasource.url=jdbc:mysql://localhost:3306/gerenciamento
spring.datasource.username=root
spring.datasource.password=N6mr4tcngw@

server.servlet.context-path=/api/v1.0

#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring,jpa.properties.hibernate.format_sql=true
